---
- name: Install and configure Apache web server
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Deploy web application
      copy:
        src: ../app/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: Ensure proper permissions on web directory
      file:
        path: /var/www/html
        state: directory
        owner: root
        group: root
        mode: '0755'
